import cron from "node-cron";
import { aiService } from "../../../common/utils/aiService.js";
import { resend } from "../../../lib/resend.js";
import * as rexRepository from "./rex.repository.js";

async function runWeeklyDigestForOrg(organizationId: string, recipients: string[]) {
  try {
    const datasets = await rexRepository.findDatasets(organizationId);

    const metricKeys = ["mrr", "arr", "burn", "cash", "churn_rate", "growth_rate", "new_customers", "cac", "ltv"];
    const metrics: Record<string, number> = {};

    for (const key of metricKeys) {
      const ds = datasets
        .filter((d) => d.metricKey === key)
        .sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime())[0];
      if (ds) {
        const pts = ds.points as Array<{ date: string; value: number }>;
        if (pts.length) metrics[key] = pts[pts.length - 1].value;
      }
    }

    if (Object.keys(metrics).length === 0) return;

    const { data } = await aiService.post<Record<string, unknown>>("/ai/rex/weekly-digest", {
      user_id: "system",
      organization_id: organizationId,
      metrics,
      prev_week: {},
    });

    await rexRepository.createAssistantMessage({
      organizationId,
      userId: "system",
      content: (data.headline as string) ?? "Weekly digest generated.",
      customInput: { actionId: "rex:weekly-digest", input: { metrics }, result: data },
    });

    if (recipients.length > 0) {
      const headline = (data.headline as string) ?? "Your weekly CFO digest";
      const focusItems = (data.focus_this_week as string[]) ?? [];
      await resend.emails.send({
        from: process.env.EMAIL_USER!,
        to: recipients,
        subject: `REX Weekly Digest — ${headline}`,
        html: `
          <h2>${headline}</h2>
          ${focusItems.length ? `<h3>Focus this week</h3><ul>${focusItems.map((f) => `<li>${f}</li>`).join("")}</ul>` : ""}
          <p style="color:#888;font-size:12px;">Generated by REX, your AI CFO.</p>
        `,
      });
    }
  } catch (err) {
    console.error(`[rex-cron] digest failed for org ${organizationId}:`, err);
  }
}

export async function runWeeklyDigestNow() {
  const orgs = await rexRepository.findAllOrgsWithDigestEnabled();
  await Promise.allSettled(
    orgs.map((s) => runWeeklyDigestForOrg(s.organizationId, s.weeklyDigestRecipients))
  );
}

export function startRexCron() {
  // Every Monday at 09:00 UTC
  cron.schedule("0 9 * * 1", () => {
    void runWeeklyDigestNow();
  });
  console.log("[rex-cron] Weekly digest scheduled — every Monday 09:00 UTC");
}
