import type { AgentSlug } from "@/lib/types"
import type { AgentActionId } from "@/lib/types/agents"

export interface AgentActionMeta {
  id: AgentActionId
  agent: AgentSlug
  /** Trailing segment appended to /api/v1/{agent}/ */
  endpoint: string
  label: string
  description: string
  /** Lucide icon name (resolved in PlusMenu) */
  icon: string
  /** Shown as an example prompt / hint */
  example?: string
  /** Hide from the global Plus menu — surfaced contextually from result cards instead. */
  hideFromMenu?: boolean
}

export const AGENT_ACTIONS: Record<AgentSlug, AgentActionMeta[]> = {
  sage: [
    {
      id: "sage:keyword-research",
      agent: "sage",
      endpoint: "keyword-research",
      label: "Keyword research",
      description: "Discover SEO keywords and intent clusters around a seed topic.",
      icon: "Search",
      example: "AI productivity tools for founders",
    },
    {
      id: "sage:generate-blog",
      agent: "sage",
      endpoint: "generate-blog",
      label: "Generate blog post",
      description: "Draft a full SEO-optimized blog post with meta tags and schema.",
      icon: "FileText",
    },
    {
      id: "sage:analyze-content",
      agent: "sage",
      endpoint: "analyze-content",
      label: "Audit content",
      description: "Score existing content and surface SEO improvements.",
      icon: "Gauge",
    },
    {
      id: "sage:content-brief",
      agent: "sage",
      endpoint: "content-brief",
      label: "Content brief",
      description: "Produce a strategic content brief with competitor gap analysis.",
      icon: "ClipboardList",
    },
    {
      id: "sage:generate-blog-ideas",
      agent: "sage",
      endpoint: "generate-blog-ideas",
      label: "Blog post ideas",
      description: "Generate trending blog topics tailored to your company from the brandkit.",
      icon: "Sparkles",
    },
    {
      id: "sage:page-seo-audit",
      agent: "sage",
      endpoint: "page-audit",
      label: "Page SEO Audit",
      description: "Deep-dive audit of a single URL — technical, speed, image, on-page, E-E-A-T, and competitive analysis.",
      icon: "Gauge",
      example: "https://yoursite.com/blog/post",
    },
    {
      id: "sage:site-audit",
      agent: "sage",
      endpoint: "site-audit",
      label: "Site Audit",
      description: "Full-site SEO health check — crawls sitemap, checks HTTP status, detects orphan pages and cannibalization.",
      icon: "Globe",
      example: "yoursite.com",
    },
  ],
  maya: [
    {
      id: "maya:campaign",
      agent: "maya",
      endpoint: "campaign",
      label: "Create Product Campaign",
      description: "Generate a cohesive batch of product campaign photos from a single product image.",
      icon: "Rocket",
    },
    {
      id: "maya:generate-ideas",
      agent: "maya",
      endpoint: "generate-ideas",
      label: "Generate post ideas",
      description: "Platform-native content ideas with hooks and predicted engagement.",
      icon: "Sparkles",
    },
    {
      id: "maya:draft-content",
      agent: "maya",
      endpoint: "draft-content",
      label: "Draft a post",
      description: "Full ready-to-publish social post with optional AI image.",
      icon: "PenLine",
    },
    {
      id: "maya:draft-carousel",
      agent: "maya",
      endpoint: "draft-carousel",
      label: "Draft a carousel",
      description: "Multi-slide carousel post with connected images for any platform.",
      icon: "GalleryHorizontal",
      hideFromMenu: true,
    },
    {
      id: "maya:generate-variants",
      agent: "maya",
      endpoint: "generate-variants",
      label: "Adapt to other platforms",
      description: "Rewrite a post for different platforms while preserving voice.",
      icon: "Shuffle",
      hideFromMenu: true,
    },
    {
      id: "maya:revise",
      agent: "maya",
      endpoint: "revise",
      label: "Revise a post",
      description: "Refine an existing post based on feedback.",
      icon: "Wand2",
      hideFromMenu: true,
    },
    {
      id: "maya:regenerate-image",
      agent: "maya",
      endpoint: "regenerate-image",
      label: "Regenerate image",
      description: "Redraw an existing post image with a new prompt.",
      icon: "Image",
      hideFromMenu: true,
    },
    {
      id: "maya:regenerate-content",
      agent: "maya",
      endpoint: "regenerate-content",
      label: "Rewrite caption",
      description: "Rework caption copy with a new prompt.",
      icon: "RefreshCw",
      hideFromMenu: true,
    },
  ],
  scout: [
    {
      id: "scout:research-topic",
      agent: "scout",
      endpoint: "research-topic",
      label: "Research a topic",
      description: "Deep research with web scraping and synthesis.",
      icon: "Binoculars",
    },
    {
      id: "scout:research-company",
      agent: "scout",
      endpoint: "research-company",
      label: "Research a company",
      description: "Build a profile — features, pricing, SWOT, recent news.",
      icon: "Building2",
    },
    {
      id: "scout:trending-topics",
      agent: "scout",
      endpoint: "trending-topics",
      label: "Trending topics",
      description: "Discover rising topics in an industry with content angles.",
      icon: "TrendingUp",
    },
    {
      id: "scout:discover-competitors",
      agent: "scout",
      endpoint: "discover-competitors",
      label: "Discover competitors",
      description: "Find competitors in your market using live web research. Save them to your watchlist.",
      icon: "Crosshair",
      example: "AI productivity tools for startup founders",
    },
  ],
  rex: [
    {
      id: "rex:query-dataset",
      agent: "rex",
      endpoint: "datasets/query",
      label: "Ask about a dataset",
      description: "Ask any natural language question about an uploaded CSV or Excel file.",
      icon: "MessageSquare",
    },
    {
      id: "rex:analyze-dataset",
      agent: "rex",
      endpoint: "datasets/analyze",
      label: "Analyze dataset",
      description: "Full AI-powered analysis of any dataset — insights, patterns, and business recommendations.",
      icon: "Sparkles",
    },
    {
      id: "rex:generate-report",
      agent: "rex",
      endpoint: "datasets/report",
      label: "Generate dataset report",
      description: "Create a comprehensive multi-section DOCX report with charts, narratives, and strategic takeaways from any uploaded dataset.",
      icon: "FileDown",
    },
    {
      id: "rex:analyze-metrics",
      agent: "rex",
      endpoint: "analyze-metrics",
      label: "Analyze metrics",
      description: "Trend, anomaly, and health analysis across your KPIs.",
      icon: "LineChart",
    },
    {
      id: "rex:forecast",
      agent: "rex",
      endpoint: "forecast",
      label: "Forecast a metric",
      description: "Project a metric forward with confidence bands.",
      icon: "TrendingUp",
    },
    {
      id: "rex:financial-analysis",
      agent: "rex",
      endpoint: "financial-analysis",
      label: "Financial analysis",
      description: "MRR, ARR, churn, burn, runway and recommendations.",
      icon: "DollarSign",
      hideFromMenu: true,
    },
    {
      id: "rex:compile-briefing",
      agent: "rex",
      endpoint: "compile-briefing",
      label: "Executive briefing",
      description: "Stitch metrics + agent summaries into one briefing.",
      icon: "Newspaper",
      hideFromMenu: true,
    },
    {
      id: "rex:runway",
      agent: "rex",
      endpoint: "runway",
      label: "Runway scenarios",
      description: "Calculate cash runway with base, optimistic, and pessimistic scenarios.",
      icon: "Hourglass",
      hideFromMenu: true,
    },
    {
      id: "rex:unit-economics",
      agent: "rex",
      endpoint: "unit-economics",
      label: "Unit economics",
      description: "Compute CAC, LTV, LTV:CAC ratio, and payback period with benchmarks.",
      icon: "Coins",
      hideFromMenu: true,
    },
    {
      id: "rex:scenario",
      agent: "rex",
      endpoint: "scenario",
      label: "What-if scenarios",
      description: "Model burn, MRR, and growth changes to compare runway outcomes.",
      icon: "GitBranch",
      hideFromMenu: true,
    },
    {
      id: "rex:weekly-digest",
      agent: "rex",
      endpoint: "weekly-digest",
      label: "Weekly CFO digest",
      description: "Monday morning digest with WoW changes, alerts, and 3 focus actions.",
      icon: "CalendarRange",
      hideFromMenu: true,
    },
    {
      id: "rex:investor-update",
      agent: "rex",
      endpoint: "investor-update",
      label: "Investor update",
      description: "Draft a structured investor update email with metrics and asks.",
      icon: "Mail",
      hideFromMenu: true,
    },
    {
      id: "rex:variance",
      agent: "rex",
      endpoint: "variance",
      label: "Variance analysis",
      description: "Compare an actual dataset against a budget dataset month by month.",
      icon: "AlertTriangle",
      hideFromMenu: true,
    },
    {
      id: "rex:board-deck",
      agent: "rex",
      endpoint: "board-deck",
      label: "Board deck",
      description: "Auto-generate a structured investor-ready board update with print-friendly HTML.",
      icon: "FileText",
      hideFromMenu: true,
    },
  ],
  lex: [
    {
      id: "lex:upload-source",
      agent: "lex",
      endpoint: "sources/upload",
      label: "Upload a document",
      description: "Upload a PDF — stored in R2 and indexed for analysis.",
      icon: "Upload",
    },
    {
      id: "lex:analyze-contract",
      agent: "lex",
      endpoint: "analyze-contract",
      label: "Analyze a contract",
      description: "Risk analysis, unusual clauses, missing protections.",
      icon: "ShieldAlert",
    },
    {
      id: "lex:query-document",
      agent: "lex",
      endpoint: "query-document",
      label: "Ask a document",
      description: "Ask a question about an uploaded document.",
      icon: "MessageCircleQuestion",
    },
    {
      id: "lex:draft-document",
      agent: "lex",
      endpoint: "draft-document",
      label: "Draft a document",
      description: "Generate a legal template — NDA, SaaS MSA, offer letter…",
      icon: "FileSignature",
    },
    {
      id: "lex:explain",
      agent: "lex",
      endpoint: "explain",
      label: "Explain legal text",
      description: "Plain-English explanation with key terms glossary.",
      icon: "BookOpen",
    },
    {
      id: "lex:legal-research",
      agent: "lex",
      endpoint: "legal-research",
      label: "Research a legal question",
      description: "Applicable laws, cases, and practical guidance for a jurisdiction.",
      icon: "Scale",
    },
    {
      id: "lex:compliance-check",
      agent: "lex",
      endpoint: "compliance-check",
      label: "Compliance check",
      description: "Evaluate practice or doc against GDPR, CCPA, SOC2, HIPAA.",
      icon: "ShieldCheck",
    },
  ],
  vega: [
    {
      id: "vega:process-inbox",
      agent: "vega",
      endpoint: "process-inbox",
      label: "Triage inbox",
      description: "Prioritize, label, and optionally draft replies.",
      icon: "Inbox",
    },
    {
      id: "vega:draft-reply",
      agent: "vega",
      endpoint: "draft-reply",
      label: "Draft a reply",
      description: "Reply in your voice to a specific email.",
      icon: "Reply",
    },
    {
      id: "vega:calendar-summary",
      agent: "vega",
      endpoint: "calendar-summary",
      label: "Calendar summary",
      description: "Agenda, conflicts, and free slots for the next week.",
      icon: "CalendarDays",
    },
    {
      id: "vega:create-event",
      agent: "vega",
      endpoint: "create-event",
      label: "Schedule an event",
      description: "Parse a plain-English event and create it on your calendar.",
      icon: "CalendarPlus",
    },
    {
      id: "vega:compose-email",
      agent: "vega",
      endpoint: "compose-email",
      label: "Compose an email",
      description: "Draft a new outbound Gmail — saves directly as a Gmail draft.",
      icon: "Mail",
    },
    {
      id: "vega:executive-briefing",
      agent: "vega",
      endpoint: "executive-briefing",
      label: "Executive briefing",
      description: "Daily exec briefing — urgent actions, schedule, focus.",
      icon: "Sun",
    },
  ],
}

export function findAction(id: AgentActionId): AgentActionMeta | undefined {
  for (const list of Object.values(AGENT_ACTIONS)) {
    const a = list.find((x) => x.id === id)
    if (a) return a
  }
  return undefined
}
