export const AGENT_PROOFS = [
  {
    name: "Lex",
    role: "Legal Assistant",
    file: "/agents/lex.jpeg",
    accent: "#8A8AF0",
    does: "Flags contract risk, explains obligations, and turns legal fine print into clear next steps.",
    saves: "Turns legal fine print into a plain-English risk list.",
    timeSaved: "Saves teams 2+ hours daily",
    shortTime: "6h review",
    tasks: [
      "Spots risky clauses before signing",
      "Summarizes obligations in plain English",
      "Drafts the email your lawyer wants",
    ],
  },
  {
    name: "Maya",
    role: "Content & Marketing",
    file: "/agents/maya.jpeg",
    accent: "#F06464",
    does: "Turns campaigns into platform-ready posts, carousels, variants, and launch ideas.",
    saves: "Drafts posts, carousels, variants, and campaign image angles.",
    timeSaved: "Saves teams 4+ hours daily",
    shortTime: "4h content",
    tasks: [
      "Turns rough ideas into platform-native posts",
      "Writes carousel slides with a sharp hook",
      "Creates campaign angles for every channel",
    ],
  },
  {
    name: "Rex",
    role: "Data Analyst & Finance",
    file: "/agents/rex.jpeg",
    accent: "#1DBC87",
    does: "Detects revenue leaks, forecasts runway, and turns numbers into decisions.",
    saves: "Explains trends, runway, forecasts, and investor-ready numbers.",
    timeSaved: "Saves teams 5+ hours daily",
    shortTime: "5h numbers",
    tasks: [
      "Finds metric spikes and slow leaks",
      "Models runway without spreadsheet panic",
      "Drafts investor updates from the numbers",
    ],
  },
  {
    name: "Sage",
    role: "SEO Specialist",
    file: "/agents/sage.jpeg",
    accent: "#F79FD4",
    does: "Finds search opportunities, shapes briefs, and turns keywords into content plans.",
    saves: "Clusters keywords, finds gaps, and shapes blog angles.",
    timeSaved: "Saves teams 3+ hours daily",
    shortTime: "3h planning",
    tasks: [
      "Clusters keywords by search intent",
      "Builds briefs writers can actually follow",
      "Finds content gaps competitors missed",
    ],
  },
  {
    name: "Scout",
    role: "Research & Strategist",
    file: "/agents/scout.jpeg",
    accent: "#F5C518",
    does: "Tracks competitors, spots market shifts, and surfaces trends before they peak.",
    saves: "Surfaces market shifts, trending topics, and competitor moves.",
    timeSaved: "Saves teams 3+ hours daily",
    shortTime: "4h research",
    tasks: [
      "Tracks rival moves before they surprise you",
      "Finds trend angles worth posting about",
      "Turns market noise into a short briefing",
    ],
  },
  {
    name: "Vega",
    role: "Executive Assistant",
    file: "/agents/vega.jpeg",
    accent: "#6FCDE8",
    does: "Prioritizes email, finds calendar conflicts, and prepares the day before it starts.",
    saves: "Ranks email, drafts replies, spots conflicts, and books meetings.",
    timeSaved: "Saves teams 2+ hours daily",
    shortTime: "2h admin",
    tasks: [
      "Ranks urgent emails before the day starts",
      "Drafts replies that sound like you",
      "Finds calendar conflicts and clean slots",
    ],
  },
] as const
