export type VideoTemplateCategory =
  | "UGC & Talking-Head Ads"
  | "Studio Product Shoots"
  | "Product Journey Films"
  | "Lifestyle & In-Context"
  | "Demo & Feature Ads"
  | "Offer & Launch Ads"
  | "Funky Narrative Shorts"

export interface VideoPromptTemplate {
  id: string
  slashCommand: string
  label: string
  category: VideoTemplateCategory
  description: string
  promptTemplate: string
}

function toLabel(slashCommand: string): string {
  return slashCommand
    .slice(1)
    .split(" ")
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join(" ")
}

function t(
  id: string,
  slashCommand: string,
  category: VideoTemplateCategory,
  description: string,
  promptTemplate: string,
): VideoPromptTemplate {
  return { id, slashCommand, label: toLabel(slashCommand), category, description, promptTemplate }
}

export const VIDEO_PROMPT_TEMPLATES: VideoPromptTemplate[] = [
  // 01 UGC & Talking-Head Ads
  t("ugc-ad", "/ugc ad", "UGC & Talking-Head Ads",
    "A creator holds your product to camera and gives a 15-second honest review in a real bedroom setting.",
    "A creator holds {{product}} up to the camera and gives a 15-second honest review in a real bedroom setting, warm and casual talking-head style."),
  t("unboxing", "/unboxing", "UGC & Talking-Head Ads",
    "First-person hands opening your packaging on a bed, slow reveal, natural window light.",
    "First-person hands slowly open the packaging of {{product}} on a bed, slow satisfying reveal, natural window light."),
  t("get-ready-with-me", "/get ready with me", "UGC & Talking-Head Ads",
    "A person adds your product into their morning routine while chatting to the camera.",
    "A person incorporates {{product}} into their morning get-ready routine while chatting casually to the camera."),
  t("first-impression", "/first impression", "UGC & Talking-Head Ads",
    "Someone tries your product for the first time on camera, genuine surprised reaction.",
    "Someone tries {{product}} for the first time on camera and reacts with a genuine, surprised expression."),
  t("tiktok-testimonial", "/tiktok testimonial", "UGC & Talking-Head Ads",
    "Fast-cut talking-head raving about your product with on-screen captions and a trending feel.",
    "A fast-cut talking-head video raving about {{product}}, with bold on-screen captions and a trending, high-energy social feel."),
  t("skeptic-to-fan", "/skeptic to fan", "UGC & Talking-Head Ads",
    "A doubtful buyer tries your product mid-video and visibly changes their mind.",
    "A visibly doubtful buyer tries {{product}} mid-video and their expression changes from skeptical to won-over."),
  t("day-in-my-life", "/day in my life", "UGC & Talking-Head Ads",
    "Your product appears naturally three times across a person's realistic day.",
    "{{product}} appears naturally three separate times across a person's realistic day-in-the-life montage."),
  t("text-me-back-reply", "/text me back reply", "UGC & Talking-Head Ads",
    "Creator replies to a fake comment on screen and demos your product to answer it.",
    "A creator reads a comment shown on screen and replies by demoing {{product}} to answer it directly."),
  t("honest-review", "/honest review", "UGC & Talking-Head Ads",
    "Balanced review that names one small flaw before landing on why they'd rebuy.",
    "A balanced talking-head review of {{product}} that names one small flaw before landing on why they'd buy it again."),
  t("what-i-ordered-vs-got", "/what i ordered vs got", "UGC & Talking-Head Ads",
    "Split reaction showing the product beating low expectations, satisfied close.",
    "A split-screen 'what I ordered vs what I got' reaction showing {{product}} beating low expectations, ending on a satisfied close-up."),
  t("three-reasons", "/three reasons", "UGC & Talking-Head Ads",
    "Creator counts three quick reasons to buy on their fingers, each with a product cut.",
    "A creator counts three quick reasons to buy {{product}} on their fingers, cutting to a product shot on each reason."),
  t("packing-an-order", "/packing an order", "UGC & Talking-Head Ads",
    "Small-business owner packs your product for a customer with a warm voiceover.",
    "A small-business owner carefully packs {{product}} into an order box for a customer, with a warm, personal voiceover."),
  t("restock-haul", "/restock haul", "UGC & Talking-Head Ads",
    "Someone shows a shelf being restocked with multiples of your product.",
    "A shelf is restocked with multiples of {{product}}, shown in a satisfying haul-style sequence."),
  t("asmr-review", "/asmr review", "UGC & Talking-Head Ads",
    "Close, quiet ASMR handling of your product with whispered description.",
    "A close-up, quiet ASMR-style handling of {{product}}, with soft whispered description and crisp tactile sound."),
  t("gift-reaction", "/gift reaction", "UGC & Talking-Head Ads",
    "Someone unwraps your product as a gift and reacts with real delight.",
    "Someone unwraps {{product}} as a surprise gift and reacts with genuine, delighted surprise."),
  t("before-work-routine", "/before work routine", "UGC & Talking-Head Ads",
    "Product used in a rushed but relatable get-ready-for-work sequence.",
    "{{product}} is used in a rushed but relatable get-ready-for-work morning sequence."),
  t("i-was-wrong", "/i was wrong", "UGC & Talking-Head Ads",
    "Creator admits they judged the product early, then shows why they kept it.",
    "A creator admits on camera that they judged {{product}} too early, then explains why they ended up keeping it."),
  t("duet-reaction", "/duet reaction", "UGC & Talking-Head Ads",
    "Side-by-side layout reacting to your product being used, nodding along.",
    "A side-by-side duet-style layout where a creator reacts to {{product}} being used, nodding along in agreement."),
  t("late-night-order", "/late night order", "UGC & Talking-Head Ads",
    "Cozy voiceover of someone impulse-buying your product at midnight, no regret.",
    "A cozy, relatable voiceover follows someone impulse-buying {{product}} at midnight, with zero regret the next morning."),
  t("friend-recommend", "/friend recommend", "UGC & Talking-Head Ads",
    "Person films a casual selfie video 'telling a friend' about your product.",
    "A person films a casual selfie-style video as if personally telling a friend about {{product}}."),

  // 02 Studio Product Shoots
  t("productshoot-ad", "/productshoot ad", "Studio Product Shoots",
    "Your product on a seamless studio backdrop with a slow orbiting camera and soft key light.",
    "{{product}} sits on a seamless studio backdrop while the camera slowly orbits it under soft, flattering key light."),
  t("floating-product", "/floating product", "Studio Product Shoots",
    "Product hovers and slowly rotates against a solid colour, premium and minimal.",
    "{{product}} hovers weightlessly and slowly rotates against a solid colour background, premium and minimal."),
  t("spotlight-reveal", "/spotlight reveal", "Studio Product Shoots",
    "Dark set, single spotlight sweeps on to reveal your product dramatically.",
    "On a dark set, a single spotlight sweeps on to dramatically reveal {{product}}."),
  t("water-splash", "/water splash", "Studio Product Shoots",
    "Product frozen mid-splash of water droplets, crisp and high-shutter.",
    "{{product}} is frozen mid-splash surrounded by crisp water droplets, shot with a high-shutter, ultra-sharp look."),
  t("marble-slab", "/marble slab", "Studio Product Shoots",
    "Product staged on polished marble with a shallow depth-of-field push-in.",
    "{{product}} is staged on a polished marble slab as the camera does a shallow depth-of-field push-in."),
  t("gradient-studio", "/gradient studio", "Studio Product Shoots",
    "Smooth two-tone gradient background, product centred, gentle parallax.",
    "{{product}} is centred against a smooth two-tone gradient studio background with a gentle parallax camera move."),
  t("macro-detail", "/macro detail", "Studio Product Shoots",
    "Extreme close-up gliding across the texture and finish of your product.",
    "An extreme macro close-up glides slowly across the texture and finish of {{product}}."),
  t("pedestal-turn", "/pedestal turn", "Studio Product Shoots",
    "Product on a rotating pedestal, 360-degree loop with rim lighting.",
    "{{product}} sits on a rotating pedestal completing a seamless 360-degree loop with rim lighting."),
  t("silk-backdrop", "/silk backdrop", "Studio Product Shoots",
    "Flowing silk fabric behind your product moving in slow motion.",
    "Flowing silk fabric ripples behind {{product}} in slow motion, elegant and premium."),
  t("neon-edge", "/neon edge", "Studio Product Shoots",
    "Product lit with a single neon accent against matte black, moody.",
    "{{product}} is lit with a single moody neon accent against a matte black background."),
  t("glass-reflection", "/glass reflection", "Studio Product Shoots",
    "Product on a glass surface with a mirrored reflection, slow dolly.",
    "{{product}} rests on a glass surface with a crisp mirrored reflection as the camera does a slow dolly move."),
  t("color-pop", "/color pop", "Studio Product Shoots",
    "Product against its own dominant colour, punchy and scroll-stopping.",
    "{{product}} is framed against a background built from its own dominant colour, punchy and scroll-stopping."),
  t("smoke-wisp", "/smoke wisp", "Studio Product Shoots",
    "Thin smoke curls around your product in a dark, cinematic frame.",
    "Thin wisps of smoke curl slowly around {{product}} in a dark, cinematic frame."),
  t("levitating-set", "/levitating set", "Studio Product Shoots",
    "Product and its ingredients float in a suspended, weightless arrangement.",
    "{{product}} and its key ingredients float together in a suspended, weightless arrangement."),
  t("luxury-boxset", "/luxury boxset", "Studio Product Shoots",
    "Product beside open premium packaging with gold-accent lighting.",
    "{{product}} is staged beside its open premium packaging under warm gold-accent lighting."),
  t("minimal-shadow", "/minimal shadow", "Studio Product Shoots",
    "Hard directional light casting a clean geometric shadow behind the product.",
    "Hard directional light casts a clean, graphic geometric shadow behind {{product}}."),
  t("ice-and-frost", "/ice and frost", "Studio Product Shoots",
    "Product surrounded by frost and ice for a cold, fresh feel.",
    "{{product}} is surrounded by frost and fine ice crystals for a cold, fresh feel."),
  t("paper-backdrop", "/paper backdrop", "Studio Product Shoots",
    "Curved seamless paper sweep, catalogue-style beauty lighting.",
    "{{product}} sits on a curved seamless paper sweep under clean, catalogue-style beauty lighting."),
  t("liquid-pour", "/liquid pour", "Studio Product Shoots",
    "Slow-motion pour of the product or its texture into frame.",
    "A slow-motion pour of {{product}} or its texture flows gracefully into frame."),
  t("hero-rotate", "/hero rotate", "Studio Product Shoots",
    "Single continuous hero rotation with light raking across the label.",
    "A single continuous hero rotation of {{product}} as light rakes slowly across its label."),

  // 03 Product Journey Films
  t("product-journey-ad", "/product journey ad", "Product Journey Films",
    "Full arc from raw ingredients to finished product to a happy customer using it.",
    "A full story arc for {{product}}: from raw ingredients, to the finished product, to a happy customer using it."),
  t("farm-to-shelf", "/farm to shelf", "Product Journey Films",
    "Sourcing origin, through processing, to the packaged product on a shelf.",
    "{{product}}'s journey from its sourcing origin, through processing, to the packaged product sitting on a shelf."),
  t("problem-to-solution", "/problem to solution", "Product Journey Films",
    "Opens on the frustration your product solves, resolves with the product in use.",
    "Opens on the exact frustration {{product}} solves, then resolves with {{product}} in confident use."),
  t("how-its-made", "/how it's made", "Product Journey Films",
    "Behind-the-scenes montage of your product being crafted, step by step.",
    "A behind-the-scenes montage showing {{product}} being crafted, step by step."),
  t("idea-to-product", "/idea to product", "Product Journey Films",
    "Sketch or concept dissolving into the real finished product.",
    "An early sketch or concept dissolves seamlessly into the real, finished {{product}}."),
  t("one-day-with-it", "/one day with it", "Product Journey Films",
    "Product followed across a single day from morning to night.",
    "{{product}} is followed across a single day, from morning to night."),
  t("the-transformation", "/the transformation", "Product Journey Films",
    "Clear before-state, the product applied, then the after-state result.",
    "A clear before-state, {{product}} being applied, then a satisfying after-state result."),
  t("founder-story", "/founder story", "Product Journey Films",
    "Short narrated arc of why the product exists, ending on it being used.",
    "A short narrated arc of why {{product}} exists, ending on it being used in real life."),
  t("ingredient-spotlight", "/ingredient spotlight", "Product Journey Films",
    "Each key ingredient introduced, then combined into the final product.",
    "Each key ingredient of {{product}} is introduced individually, then combined into the final product."),
  t("order-to-doorstep", "/order to doorstep", "Product Journey Films",
    "Tap to buy, packed, shipped, delivered, unboxed -- the whole loop.",
    "The full loop for {{product}}: tap to buy, packed, shipped, delivered, and unboxed at the door."),
  t("season-change", "/season change", "Product Journey Films",
    "Product shown adapting across seasons or occasions in one film.",
    "{{product}} is shown adapting across different seasons or occasions within one continuous film."),
  t("first-to-hundredth", "/first to hundredth", "Product Journey Films",
    "From the first unit made to a wall of stock, growth story energy.",
    "{{product}}'s growth story: from the very first unit made to a full wall of stock."),
  t("hands-that-make-it", "/hands that make it", "Product Journey Films",
    "Close-ups of the craft and human hands building each product.",
    "Close-up shots of skilled human hands crafting {{product}}, step by step."),
  t("from-doubt-to-loyal", "/from doubt to loyal", "Product Journey Films",
    "A customer's arc from unsure to repeat buyer over several scenes.",
    "A customer's arc across several scenes: from unsure first-timer to loyal repeat buyer of {{product}}."),
  t("the-ritual", "/the ritual", "Product Journey Films",
    "Product placed inside a repeatable daily ritual, calm and aspirational.",
    "{{product}} is placed inside a calm, aspirational daily ritual."),
  t("lab-to-life", "/lab to life", "Product Journey Films",
    "Formulation or testing scenes leading to real-world everyday use.",
    "Formulation or testing scenes for {{product}} lead into real-world, everyday use."),
  t("city-to-home", "/city to home", "Product Journey Films",
    "Product travelling from store or warehouse into a cozy home.",
    "{{product}} travels from a city store or warehouse into a cozy home setting."),
  t("generations", "/generations", "Product Journey Films",
    "Product framed as passed down or shared across people over time.",
    "{{product}} is framed as something passed down or shared across people over time."),
  t("the-reveal-build", "/the reveal build", "Product Journey Films",
    "Components assembling one by one until the full product appears.",
    "Individual components assemble one by one until the full {{product}} appears."),
  t("small-batch", "/small batch", "Product Journey Films",
    "Intimate small-batch making process ending on the labelled product.",
    "An intimate small-batch making process for {{product}}, ending on the finished, labelled product."),

  // 04 Lifestyle & In-Context
  t("lifestyle-ad", "/lifestyle ad", "Lifestyle & In-Context",
    "Product used naturally in an aspirational but believable real-life setting.",
    "{{product}} is used naturally in an aspirational but believable real-life setting."),
  t("morning-kitchen", "/morning kitchen", "Lifestyle & In-Context",
    "Product on a sunlit kitchen counter during a relaxed breakfast scene.",
    "{{product}} sits on a sunlit kitchen counter during a relaxed breakfast scene."),
  t("desk-setup", "/desk setup", "Lifestyle & In-Context",
    "Product styled into a clean, productive work-from-home desk.",
    "{{product}} is styled into a clean, productive work-from-home desk setup."),
  t("gym-bag", "/gym bag", "Lifestyle & In-Context",
    "Product pulled from a gym bag and used mid-workout routine.",
    "{{product}} is pulled from a gym bag and used mid-workout."),
  t("travel-carry", "/travel carry", "Lifestyle & In-Context",
    "Product packed and used on a trip -- airport, hotel, on the go.",
    "{{product}} is packed and used on a trip -- airport, hotel room, and on the go."),
  t("cozy-evening", "/cozy evening", "Lifestyle & In-Context",
    "Warm, low-light evening scene with the product in a wind-down moment.",
    "A warm, low-light evening scene features {{product}} during a quiet wind-down moment."),
  t("outdoor-picnic", "/outdoor picnic", "Lifestyle & In-Context",
    "Product featured in a bright outdoor picnic or park setting.",
    "{{product}} is featured in a bright outdoor picnic or park setting."),
  t("date-night", "/date night", "Lifestyle & In-Context",
    "Product used while getting ready for a night out, glamorous mood.",
    "{{product}} is used while getting ready for a night out, glamorous mood."),
  t("family-table", "/family table", "Lifestyle & In-Context",
    "Product shared around a lively family table scene.",
    "{{product}} is shared around a lively family table scene."),
  t("self-care-sunday", "/self care sunday", "Lifestyle & In-Context",
    "Slow, indulgent self-care sequence built around your product.",
    "A slow, indulgent self-care Sunday sequence is built around {{product}}."),
  t("on-the-commute", "/on the commute", "Lifestyle & In-Context",
    "Product used realistically during a daily commute.",
    "{{product}} is used realistically during a daily commute."),
  t("weekend-reset", "/weekend reset", "Lifestyle & In-Context",
    "Product inside a satisfying weekend cleaning-and-reset montage.",
    "{{product}} appears inside a satisfying weekend cleaning-and-reset montage."),
  t("coffee-shop", "/coffee shop", "Lifestyle & In-Context",
    "Product placed on a cafe table with ambient background life.",
    "{{product}} is placed on a cafe table with ambient background life around it."),
  t("beach-day", "/beach day", "Lifestyle & In-Context",
    "Product in a sunny beach or poolside lifestyle frame.",
    "{{product}} appears in a sunny beach or poolside lifestyle frame."),
  t("study-session", "/study session", "Lifestyle & In-Context",
    "Product supporting a focused late-night study or hustle scene.",
    "{{product}} supports a focused late-night study or hustle scene."),

  // 05 Demo & Feature Ads
  t("demo-ad", "/demo ad", "Demo & Feature Ads",
    "Straightforward demonstration of your product's core function and result.",
    "A straightforward demonstration of {{product}}'s core function and result."),
  t("before-after", "/before after", "Demo & Feature Ads",
    "Clean split or wipe from the before state to the product-driven after.",
    "A clean split or wipe transition from the before state to the {{product}}-driven after."),
  t("how-to-use", "/how to use", "Demo & Feature Ads",
    "Simple three-step how-to with numbered on-screen captions.",
    "A simple three-step how-to for {{product}} with numbered on-screen captions."),
  t("satisfying-result", "/satisfying result", "Demo & Feature Ads",
    "Focus entirely on the most satisfying moment the product produces.",
    "The camera focuses entirely on the single most satisfying moment {{product}} produces."),
  t("feature-callout", "/feature callout", "Demo & Feature Ads",
    "Camera moves across the product with animated labels on each feature.",
    "The camera moves across {{product}} with animated labels calling out each feature."),
  t("speed-test", "/speed test", "Demo & Feature Ads",
    "Product delivering its result fast, with an on-screen timer.",
    "{{product}} delivers its result fast, tracked by an on-screen timer."),
  t("durability-test", "/durability test", "Demo & Feature Ads",
    "Product put under stress to prove it holds up.",
    "{{product}} is put under visible stress to prove it holds up."),
  t("comparison-split", "/comparison split", "Demo & Feature Ads",
    "Your product beside the old way, side-by-side, product clearly winning.",
    "{{product}} is shown side-by-side against the old way, clearly winning the comparison."),
  t("one-swipe", "/one swipe", "Demo & Feature Ads",
    "A single application or use showing an immediate visible payoff.",
    "A single application or use of {{product}} shows an immediate, visible payoff."),
  t("close-up-proof", "/close up proof", "Demo & Feature Ads",
    "Macro proof shot of the exact result buyers are skeptical about.",
    "A macro proof shot of {{product}} showing the exact result skeptical buyers want to see."),
  t("texture-reveal", "/texture reveal", "Demo & Feature Ads",
    "Slow reveal of the product's texture, swatch or finish.",
    "A slow, close reveal of {{product}}'s texture, swatch, or finish."),
  t("multi-use", "/multi use", "Demo & Feature Ads",
    "Rapid montage of three different ways to use the same product.",
    "A rapid montage of three different ways to use {{product}}."),
  t("the-fix", "/the fix", "Demo & Feature Ads",
    "Product solving a specific annoying problem in real time.",
    "{{product}} solves a specific, annoying problem in real time."),
  t("results-in-7-days", "/results in 7 days", "Demo & Feature Ads",
    "Day-by-day progression card sequence ending on the final result.",
    "A day-by-day progression card sequence for {{product}}, ending on the final result."),
  t("tap-through-steps", "/tap through steps", "Demo & Feature Ads",
    "Quick tappable-looking steps showing setup to finish.",
    "Quick, tappable-looking steps show {{product}} from setup to finish."),

  // 06 Offer & Launch Ads
  t("offer-ad", "/offer ad", "Offer & Launch Ads",
    "Bold, fast-cut ad built around a single clear discount or bundle.",
    "A bold, fast-cut ad for {{product}} built around a single clear discount or bundle."),
  t("new-drop", "/new drop", "Offer & Launch Ads",
    "Hype-style launch teaser revealing a new product with kinetic type.",
    "A hype-style launch teaser reveals {{product}} with kinetic on-screen type."),
  t("bundle-deal", "/bundle deal", "Offer & Launch Ads",
    "Three products animating together into one value bundle.",
    "Three {{product}} items animate together into one value bundle."),
  t("festive-ad", "/festive ad", "Offer & Launch Ads",
    "Occasion-themed ad (Diwali, Rakhi, wedding) with festive styling.",
    "An occasion-themed ad for {{product}} (festival or wedding season) with festive styling."),
  t("limited-stock", "/limited stock", "Offer & Launch Ads",
    "Urgency-driven ad with a countdown and low-stock framing.",
    "An urgency-driven ad for {{product}} with a countdown and low-stock framing."),
  t("flash-sale", "/flash sale", "Offer & Launch Ads",
    "High-energy flash-sale ad with a big number and a hard CTA.",
    "A high-energy flash-sale ad for {{product}} with a big discount number and a hard call-to-action."),
  t("free-gift", "/free gift", "Offer & Launch Ads",
    "Gift-with-purchase ad showing the bonus item revealed.",
    "A gift-with-purchase ad for {{product}} revealing the bonus item."),
  t("coming-soon", "/coming soon", "Offer & Launch Ads",
    "Mysterious pre-launch teaser that hides then hints at the product.",
    "A mysterious pre-launch teaser that hides then hints at {{product}}."),
  t("price-reveal", "/price reveal", "Offer & Launch Ads",
    "Product shown first, then a satisfying price-drop reveal.",
    "{{product}} is shown first, then a satisfying price-drop reveal follows."),
  t("back-in-stock", "/back in stock", "Offer & Launch Ads",
    "Restock announcement with an excited, in-demand tone.",
    "A restock announcement for {{product}} with an excited, in-demand tone."),
  t("combo-builder", "/combo builder", "Offer & Launch Ads",
    "Customer 'building' their perfect combo from your range.",
    "A customer 'builds' their perfect combo from your {{product}} range."),
  t("first-order-deal", "/first order deal", "Offer & Launch Ads",
    "New-customer welcome-offer ad with an entry-price hook.",
    "A new-customer welcome-offer ad for {{product}} with an entry-price hook."),
  t("last-chance", "/last chance", "Offer & Launch Ads",
    "End-of-sale urgency ad with a closing-soon countdown.",
    "An end-of-sale urgency ad for {{product}} with a closing-soon countdown."),
  t("anniversary-sale", "/anniversary sale", "Offer & Launch Ads",
    "Celebratory brand-anniversary sale ad with milestone energy.",
    "A celebratory brand-anniversary sale ad for {{product}} with milestone energy."),
  t("gift-guide", "/gift guide", "Offer & Launch Ads",
    "Product positioned as the obvious pick in a seasonal gift guide.",
    "{{product}} is positioned as the obvious pick in a seasonal gift guide."),

  // 07 Funky Narrative Shorts -- original/generic characters only, never branded IP
  t("caped-rooftop-run", "/caped rooftop run", "Funky Narrative Shorts",
    "A masked freelance superhero swings between rooftops, grabs your product from a corner stand, and gives a thumbs-up to camera.",
    "A masked, original superhero (no branded likeness) swings between city rooftops, lands, grabs {{product}} from a corner stand, takes a sip or bite, and gives a confident thumbs-up to camera as the logo fades in."),
  t("robot-courier", "/robot courier", "Funky Narrative Shorts",
    "A retro delivery robot rolls through a neon city street and pauses to admire your product in the light.",
    "A friendly retro delivery robot rolls through a neon-lit city street, delivers a package containing {{product}}, and pauses to admire it in the light before rolling off as the logo appears."),
  t("time-loop-taste-test", "/time loop taste test", "Funky Narrative Shorts",
    "A curious time-traveler keeps reliving the same afternoon just to try your product again.",
    "A curious time-traveler keeps reliving the same afternoon just to try {{product}} again, growing more delighted each loop, ending on the logo as the loop finally breaks."),
  t("masked-skater-trick", "/masked skater trick", "Funky Narrative Shorts",
    "A caped skater lands a trick, pulls your product from a backpack, and skates off into a sunset.",
    "A caped, original skater character lands a trick, pulls {{product}} from a backpack, takes a satisfied sip or bite, and skates off into a sunset as the logo animates in."),
  t("barista-superhero", "/barista superhero", "Funky Narrative Shorts",
    "A cape-wearing barista pours your product with dramatic, action-movie flair.",
    "A cape-wearing barista pours or presents {{product}} with dramatic, action-movie-style flair, framed like a hero shot, ending on the logo."),
  t("heist-for-flavor", "/heist for flavor", "Funky Narrative Shorts",
    "A stylish crew pulls off a playful heist just to get their hands on your product.",
    "A stylish original crew pulls off a playful, victimless 'heist' just to get their hands on {{product}}, celebrating together as the logo reveals."),
  t("giant-monster-cameo", "/giant monster cameo", "Funky Narrative Shorts",
    "A friendly giant creature peeks over a city skyline and tries your product with delight.",
    "A friendly, original giant creature peeks over a city skyline, curiously picks up {{product}}, tries it, and grins in approval before the logo appears."),
  t("secret-agent-sip", "/secret agent sip", "Funky Narrative Shorts",
    "A spy in a sleek suit swaps a briefcase for your product mid-mission.",
    "A spy in a sleek suit swaps a briefcase for {{product}} mid-mission, takes a confident sip or bite, and winks at the camera as the logo drops."),
  t("time-freeze-unboxing", "/time freeze unboxing", "Funky Narrative Shorts",
    "Everything in the scene freezes except a person unboxing your product in real time.",
    "Everything in the scene freezes in place except one person, who moves in real time to unbox {{product}} before the logo appears and time resumes."),
  t("superhero-landing", "/superhero landing", "Funky Narrative Shorts",
    "A caped hero lands hard on a rooftop and casually reaches for your product.",
    "A caped, original superhero lands hard on a rooftop, dusts off, and casually reaches for {{product}} as the city skyline and logo fade in behind them."),
  t("alien-first-taste", "/alien first taste", "Funky Narrative Shorts",
    "A curious alien visitor tries your product for the first time on Earth.",
    "A curious, friendly alien visitor tries {{product}} for the first time on Earth and reacts with delighted disbelief as the logo appears."),
  t("wizards-brew", "/wizard's brew", "Funky Narrative Shorts",
    "A whimsical wizard conjures your product out of sparkling magic dust.",
    "A whimsical wizard conjures {{product}} out of sparkling magic dust in a cozy workshop, ending on a satisfied nod and the logo."),
  t("parkour-delivery", "/parkour delivery", "Funky Narrative Shorts",
    "A free-runner vaults across rooftops carrying your product to reveal it to camera.",
    "A free-runner vaults across rooftops carrying {{product}}, landing perfectly in front of the camera to reveal it as the logo animates in."),
  t("retro-superhero-ad", "/retro superhero ad", "Funky Narrative Shorts",
    "An original comic-book-styled hero freezes mid-action to hold up your product to camera.",
    "An original, comic-book-styled hero (no branded likeness) freezes mid-action to hold {{product}} up directly to camera, with comic-panel transitions leading to the logo."),
  t("monster-truck-reveal", "/monster truck reveal", "Funky Narrative Shorts",
    "An oversized monster truck crashes through a wall to reveal your product on a pedestal.",
    "An oversized, over-the-top monster truck crashes through a wall to reveal {{product}} sitting triumphantly on a pedestal as the logo appears."),
]

export function expandTemplate(template: VideoPromptTemplate, customization?: string): string {
  const trimmed = customization?.trim()
  if (!trimmed) return template.promptTemplate.replaceAll("{{product}}", "the product")
  const expanded = template.promptTemplate.replaceAll("{{product}}", trimmed)
  return expanded === template.promptTemplate ? `${expanded} Featuring ${trimmed}.` : expanded
}
